/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pr2.hashmap.Pokemon;
import sun.audio.AudioData;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.audio.ContinuousAudioDataStream;

/**
 *
 * @author THOR
 */
public class Menu extends javax.swing.JFrame {

    public static Map<String, Pokemon> pokemons = new HashMap<String, Pokemon>();
    public static Map<String, Pokemon> pokemonsCapturados = new HashMap<String, Pokemon>();

    public Menu() {
        initComponents();
        
        //suena musica
        playClick("sounds/casino.wav");

        //logo titulo
        ImageIcon iconLogo = new ImageIcon("images/logo.png");
        Image newimg = iconLogo.getImage().getScaledInstance(image.getWidth(), image.getHeight(), java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        iconLogo = new ImageIcon(newimg);
        image.setIcon(iconLogo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altaBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        verBtn = new javax.swing.JButton();
        capturarBtn = new javax.swing.JButton();
        totalesBtn = new javax.swing.JButton();
        verCapturados = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        altaBtn.setText("ALTA POKEMON");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("MODIFICAR POKEMON");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        verBtn.setText("VER POKEMON");
        verBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBtnActionPerformed(evt);
            }
        });

        capturarBtn.setText("CAPTURAR POKEMON");
        capturarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarBtnActionPerformed(evt);
            }
        });

        totalesBtn.setText("TOTALES");
        totalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalesBtnActionPerformed(evt);
            }
        });

        verCapturados.setText("VER POKEMON CAPTURADOS");
        verCapturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCapturadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(verCapturados))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(verBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(altaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(capturarBtn)
                                .addComponent(modificarBtn)))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(totalesBtn)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capturarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verCapturados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalesBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        playClick("sounds/apress.wav");
        new AltaPkmn(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_altaBtnActionPerformed

    private void verBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBtnActionPerformed
        playClick("sounds/apress.wav");
        if (Menu.pokemons.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay pokemons registrados!");
        } else {
            new VerPokemon(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_verBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        playClick("sounds/apress.wav");
        if (pokemonsCapturados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay pokemons registrados!");
        } else {
            new ModificarPkmn(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void totalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalesBtnActionPerformed
        playClick("sounds/apress.wav");
        new TodosPkmns(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_totalesBtnActionPerformed

    private void capturarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarBtnActionPerformed
        playClick("sounds/apress.wav");
        if (Menu.pokemons.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay pokemons registrados!");
        } else {
            new CapturarPkmn(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_capturarBtnActionPerformed

    private void verCapturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCapturadosActionPerformed
        playClick("sounds/apress.wav");
        if (pokemonsCapturados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay pokemons capturados!");
        } else {
            new PokemonCapturados(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_verCapturadosActionPerformed

    public static void playClick(String file) {
        AudioInputStream audioInputStream = null;
        try {
            audioInputStream = AudioSystem.getAudioInputStream(new File(file).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(CapturarPkmn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CapturarPkmn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(CapturarPkmn.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                audioInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(CapturarPkmn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaBtn;
    private javax.swing.JButton capturarBtn;
    private javax.swing.JLabel image;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton totalesBtn;
    private javax.swing.JButton verBtn;
    private javax.swing.JButton verCapturados;
    // End of variables declaration//GEN-END:variables
}
