/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.HashMap;
import java.util.Map;
import pr2.hashmap.Pokemon;

/**
 *
 * @author THOR
 */
public class Menu extends javax.swing.JFrame {

    public static Map<String, Pokemon> pokemons = new HashMap<String, Pokemon>();
    public static Map<String, Pokemon> pokemonsCapturados = new HashMap<String, Pokemon>();
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altaBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        verBtn = new javax.swing.JButton();
        capturarBtn = new javax.swing.JButton();
        totalesBtn = new javax.swing.JButton();
        verCapturados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        altaBtn.setText("ALTA POKEMON");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("MODIFICAR POKEMON");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        verBtn.setText("VER POKEMON");
        verBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBtnActionPerformed(evt);
            }
        });

        capturarBtn.setText("CAPTURAR POKEMON");
        capturarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarBtnActionPerformed(evt);
            }
        });

        totalesBtn.setText("TOTALES");
        totalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalesBtnActionPerformed(evt);
            }
        });

        verCapturados.setText("VER POKEMON CAPTURADOS");
        verCapturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCapturadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(totalesBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capturarBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(verBtn)
                                    .addComponent(altaBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(modificarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(verCapturados)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(altaBtn)
                .addGap(18, 18, 18)
                .addComponent(modificarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verBtn)
                .addGap(12, 12, 12)
                .addComponent(capturarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verCapturados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(totalesBtn)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        new AltaPkmn(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_altaBtnActionPerformed

    private void verBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBtnActionPerformed
        new VerPokemon(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_verBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        new ModificarPkmn(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void totalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalesBtnActionPerformed
        new TodosPkmns(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_totalesBtnActionPerformed

    private void capturarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarBtnActionPerformed
        new CapturarPkmn(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_capturarBtnActionPerformed

    private void verCapturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCapturadosActionPerformed
        new PokemonCapturados(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_verCapturadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaBtn;
    private javax.swing.JButton capturarBtn;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton totalesBtn;
    private javax.swing.JButton verBtn;
    private javax.swing.JButton verCapturados;
    // End of variables declaration//GEN-END:variables
}
