/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.DefaultListModel;
import pr2.hashmap.Pokemon;
import pr2.hashmap.PokemonAgua;
import pr2.hashmap.PokemonPlanta;
import static views.Menu.playClick;

/**
 *
 * @author THOR
 */
public class PokemonCapturados extends javax.swing.JDialog {

    /**
     * Creates new form PokemonCapturados
     */
    public PokemonCapturados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarLista();
    }

    private void inicializarLista() {
        listPkmnCapturados.removeAll();
        DefaultListModel<String> demoList = new DefaultListModel<>();
        for (Pokemon pkmn : Menu.pokemonsCapturados.values()) {
            demoList.addElement(pkmn.getNombre());
        }
        listPkmnCapturados.setModel(demoList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPkmnCapturados = new javax.swing.JList<>();
        image = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblDefensa = new javax.swing.JLabel();
        lblPtsSalud = new javax.swing.JLabel();
        lblHabitat = new javax.swing.JLabel();
        lblTipoAgua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listPkmnCapturados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPkmnCapturadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPkmnCapturados);

        lblTipo.setText(" ");

        lblNombre.setText(" ");

        lblAtaque.setText(" ");

        lblDefensa.setText(" ");

        lblPtsSalud.setText(" ");

        lblHabitat.setText(" ");

        lblTipoAgua.setText(" ");

        jLabel1.setText("Lista pkmns capturados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addComponent(lblAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPtsSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(lblTipo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDefensa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPtsSalud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHabitat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipoAgua)
                        .addContainerGap(68, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPkmnCapturadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPkmnCapturadosMouseClicked
        playClick("sounds/apress.wav");
        Pokemon pkmnSelected = null;
        if (listPkmnCapturados.getSelectedValue() != null) {
            pkmnSelected = Menu.pokemons.get(listPkmnCapturados.getSelectedValue());
            if (pkmnSelected.getIcon() != null) {
                image.setIcon(pkmnSelected.getIcon());
            } else {
                image.setText("No hay imagen");
                image.setIcon(null);
            }
            if (pkmnSelected instanceof pr2.hashmap.PokemonAgua) {
                lblTipo.setText("Tipo: Agua");
                lblTipoAgua.setText("Agua: " + ((PokemonAgua) pkmnSelected).getTipoAgua());
            } else if (pkmnSelected instanceof pr2.hashmap.PokemonPlanta) {
                lblTipo.setText("Tipo: Planta");
                lblHabitat.setText("Habitat: " + ((PokemonPlanta) pkmnSelected).getHabitat());
            } else {
                lblTipo.setText("Tipo: Fuego");
            }
            lblNombre.setText("Nombre: " + pkmnSelected.getNombre());
            lblAtaque.setText("Ataque: " + String.valueOf(pkmnSelected.getAtaque()));
            lblDefensa.setText("Defensa: " + String.valueOf(pkmnSelected.getDefensa()));
            lblPtsSalud.setText("Pts Salud:" + String.valueOf(pkmnSelected.getPtsSalud()));
        }
    }//GEN-LAST:event_listPkmnCapturadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblDefensa;
    private javax.swing.JLabel lblHabitat;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPtsSalud;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoAgua;
    private javax.swing.JList<String> listPkmnCapturados;
    // End of variables declaration//GEN-END:variables
}
